- name: Configure webserver with nginx
  hosts: webservers
  sudo: true
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes cache_valid_time=3600

    - name: Create dir for ssl certs
      file: path=/etc/nginx/ssl state=directory

    - name: copy tls key
      copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
      notify: restart nginx

    - name: copy tls cert
      copy: src=files/nginx.crt dest={{ cert_file }}

    - name: Copy nginx conf file
      template: src=templates/nginx.conf.j2 dest={{ conf_file }}

    - name: enable Config 
      file: dest=/etc/nginx/sites-enabled/default src={{ conf_file }} state=link
      notify: restart nginx
       
    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
        mode=0644
  
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
